FROM fedora.riscv.rocks:3000/davidlt/fedora-toolbox:41

# repos are now incremental but container was not updated yet,
# workaround this here
COPY fedora-riscv-workaround.repo /etc/yum.repos.d/fedora-riscv-workaround.repo

# ostree is only here because our BuildrotoFromContainer hardcodes it,
# c.f. https://github.com/osbuild/images/blob/v0.118.0/pkg/manifest/build.go#L216
# Setting timeout and retries to be graceful with slow mirrors
RUN dnf install -y --setopt=timeout=120 --setopt=retries=10 \
    selinux-policy-targeted \
    policycoreutils \
    dosfstools \
    e2fsprogs \
    xfsprogs \
    btrfs-progs \
    ostree \
    zstd
# Our hardcoded build.go:NewBuildrootFromContainer expects a /ostree
# in the selinux labeling. workaround here for now.
RUN mkdir -p /ostree
